export { default as HTML } from './html.astro'
export { default as Swift } from './swift.astro'
export { default as CSS } from './css.astro';
export { default as JavaScript } from './javascript.astro';
export { default as TypeScript } from './type.astro';
export { default as React } from './react.astro';
export { default as Node } from './node.astro';
export { default as SQL } from './sql.astro';
export { default as Git } from './git.astro';
export { default as GitHub } from './GitHub.astro';
export { default as Tailwind } from './tailwind.astro';
export { default as Next } from './next.astro';
export { default as AstroIcon } from './astroicon.astro';
export { default as Android } from './android.astro';
export { default as Xcode } from './xcode.astro';
export { default as Csharp } from './csharp.astro';
export { default as Express } from './express.astro';
export { default as MongoDB } from './mongoDB.astro';